---
title: "Introduction to Stata"
output: html_document
---

STATA is a programming language that we will be using in ECON5060 to explore and analyze data. STATA is a powerful statistical tool that allows users to analyze data quick and easily without installing additional "packages" onto their system.

## Downloading STATA as a Carleton Student
STATA is not an open-source program, which means that there is a fee associated with downloading and using it. As a Carleton student, you will be able to download STATA without paying any additional fees. 

Please follow the steps below to download STATA onto your computer. 

1. Go to [this](https://i.carleton.ca/its-software/stata-se/) website. 
2. Click on the STATA SE 18 button. This will prompt you to sign in using your MC1 credentials. 
3. Fill in the request form with the proper information. A code will be sent to the email that you use in the form. 
4. Check your email for the donwload link and unique confirmation code. 
5. Once STATA is downloaded, enter the unique confirmation code as it appears in your email. 